### ISSUE TITLE
feature request: use docker-compose

### ISSUE THREAD

**Issue by khilman** [kernelci/kcidb-grafana#2]

**Comment by spbnick** [comment]
Have no idea how to use it, will have to learn. I presume this is not a priority right now for you?

**Comment by spbnick** [comment]
Read a little about it, and don't see yet how it would be useful, since we only have one container and it seems a simple Dockerfile could be enough. Am I missing something?

**Comment by khilman** [comment]
It just greatly simplifies the startup/shutdown etc.
Here you go: https://github.com/kernelci/kcidb-grafana/pull/7

**Comment by spbnick** [comment]
Thanks :)!
