### ISSUE TITLE
BQ dataset should be a variable

### ISSUE THREAD

**Issue by khilman** [kernelci/kcidb-grafana#4]
In the dashboards, make the BQ dataset (currently hardcoded to `kernelci02`) a variable for ease of using with development datasets.

**Comment by spbnick** [comment]
The best I've found so far is to have a "hidden constant variable" for each dashboard specifying the dataset to use. We'll have to update the value in each dashboard when changing it, but that's already much easier. If we combine it with #2's docker-compose and #5's provisioning we could update them automatically, perhaps.

**Comment by spbnick** [comment]
Alright, dashboard variables are added, it should be better now.

**Comment by spbnick** [comment]
One consequence of this is that anybody can now specify another dataset via the URL :man_facepalming:. Like this: https://staging.kernelci.org:3000/d/test/test?orgId=1&var-origin=redhat&var-origin_id=107600176&var-dataset=kernelci03

However, since all our datasets are theoretically open, it shouldn't be a problem.

**Comment by khilman** [comment]
The `var-dataset=` is perfect.  Thanks! 

I see it's working on the running instance, but don't see any changes in the repo.  Have you checked in those changes?

**Comment by khilman** [comment]
Minor issue:  If I add `&var-dataset=khilman` to the Home dashboard, when I click on one of the items that takes me to a revision or test dashboard, that variable doesn't follow.

**Comment by spbnicktest** [comment]
Well, it wasn't intended for that, I would have preferred that it wouldn't work that way at all.

However, if it speeds up development, we can make that work, although then everybody will know we specify our dataset there, not just us.

**Comment by khilman** [comment]
The variable is working well.  Closing.

**Comment by khilman** [comment]
Shouldn't this line also be using the variable?
https://github.com/kernelci/kcidb-grafana/blob/master/dashboards/Build.json#L342

**Comment by spbnick** [comment]
Not sure how I missed that, but yes, build output files, and revision patches were still using the literal dataset name. Fixed now!
